<?php

require_once dirname(__FILE__) . '/../../../Transmorph/Plugin/Abstract.php';

/**
 * Test class for Transmorph_Plugin_Abstract.
 * Generated by PHPUnit on 2011-11-25 at 21:39:07.
 */
abstract class Transmorph_Plugin_AbstractTest extends PHPUnit_Framework_TestCase
{

    /**
     * @var Transmorph_Plugin_Abstract
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        
    }

    /**
     * @covers Transmorph_Plugin_Abstract::processCallback
     */
    public function testProcessCallback()
    {
        $this->assertEquals('test', $this->object->processCallback(new Transmorph_Processor(), 'test'));
    }

    /**
     * @covers Transmorph_Plugin_Abstract::processCallbackParams
     */
    public function testProcessCallbackParams()
    {
        $cParams = array('test', 'check');
        $this->assertEquals($cParams, $this->object->processCallbackParams(new Transmorph_Processor(), $cParams));
    }

    /**
     * @covers Transmorph_Plugin_Abstract::processInputPathNode
     */
    public function testProcessInputPathNode()
    {
        $this->assertEquals('test', $this->object->processInputPathNode(new Transmorph_Processor(), 'test'));
    }

    /**
     * @covers Transmorph_Plugin_Abstract::processRule
     */
    public function testProcessLine()
    {
        $line = new Transmorph_Rule(' >> ');
        $this->assertEquals($line, $this->object->processRule(new Transmorph_Processor(), $line));
    }

    /**
     * @covers Transmorph_Plugin_Abstract::processMap
     */
    public function testProcessMap()
    {
        $map = array('test', 'check');
        $this->assertEquals($map, $this->object->processMap(new Transmorph_Processor(), $map));
    }

    /**
     * @covers Transmorph_Plugin_Abstract::processOutPutPathNode
     */
    public function testProcessOutPutPathNode()
    {
        $this->assertEquals('test', $this->object->processOutPutPathNode(new Transmorph_Processor(), 'test'));
    }

}